Upgrade passenger to 6.0.13 (#28)

diff --git a/test/passenger-app/Dockerfile b/test/passenger-app/Dockerfile
--- a/test/passenger-app/Dockerfile
+++ b/test/passenger-app/Dockerfile
@@ -1,7 +1,7 @@
 FROM ruby:2.7
 
-ARG ARG_RAILS_VERSION=6.1.3
-ARG ARG_PASSENGER_VERSION=6.0.5
+ARG ARG_RAILS_VERSION=7.0.2.4
+ARG ARG_PASSENGER_VERSION=6.0.13
 ENV RAILS_VERSION $ARG_RAILS_VERSION
 ENV PASSENGER_VERSION $ARG_PASSENGER_VERSION
 #
@@ -11,7 +11,7 @@ RUN apt-get update \
 WORKDIR /app
 # Create rails new application.
 RUN echo "gem: --no-document" > ~/.gemrc \
- && gem install rails -v ${RAILS_VERSION} || echo "ignore errors."
+  && gem install rails -v ${RAILS_VERSION} || echo "ignore errors."
 RUN rails new example || echo "ignore errors."
 
 #
@@ -22,6 +22,6 @@ RUN rails generate controller Welcome index
 
 # Passenger configuration.
 RUN echo "gem \"passenger\", \"${PASSENGER_VERSION}\", require: \"phusion_passenger/rack_handler\"" >> Gemfile \
- && bundle install
+  && bundle install
 
 ENTRYPOINT [ "/usr/local/bin/bundle","exec","passenger","start" ]
